// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


struct CardStore_;

struct CardStore {
    obx_id id;
    std::string word;
    std::vector<std::string> meanings;
    uint64_t time;
    uint64_t success;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(CardStore& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const CardStore& object);
    
        /// Read an object from a valid FlatBuffer
        static CardStore fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<CardStore> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, CardStore& outObject);
    };
};

struct CardStore_ {
    static const obx::Property<CardStore, OBXPropertyType_Long> id;
    static const obx::Property<CardStore, OBXPropertyType_String> word;
    static const obx::Property<CardStore, OBXPropertyType_StringVector> meanings;
    static const obx::Property<CardStore, OBXPropertyType_Long> time;
    static const obx::Property<CardStore, OBXPropertyType_Long> success;
};

