// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "CardStore", 1, 8312940545173196821);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8513981230467018490);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "word", OBXPropertyType_String, 2, 7574171527671032860);
    obx_model_property_flags(model, (OBXPropertyFlags) (OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE));
    obx_model_property_index_id(model, 1, 5161161862006283302);
    obx_model_property(model, "meanings", OBXPropertyType_StringVector, 3, 6444422950567900145);
    obx_model_property(model, "time", OBXPropertyType_Long, 4, 6682120493231345857);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "success", OBXPropertyType_Long, 5, 880767913521516613);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_entity_last_property_id(model, 5, 880767913521516613);
    
    obx_model_last_entity_id(model, 1, 8312940545173196821);
    obx_model_last_index_id(model, 1, 5161161862006283302);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
